from django.contrib import admin
from .models import FuelStation

@admin.register(FuelStation)
class FuelStationAdmin(admin.ModelAdmin):
    # Columns to display in the admin list view
    list_display = ('name', 'city', 'state', 'price', 'latitude', 'longitude')
    
    # Adds a search bar to search by name, city, state, or OPIS ID
    search_fields = ('name', 'city', 'state', 'opis_id')
    
    # Adds a filter sidebar to easily filter stations by state
    list_filter = ('state',)
    
    # Makes the list view read-only for coordinates to prevent accidental edits 
    # (since they are generated by the geocoder)
    readonly_fields = ('latitude', 'longitude')